# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: LuluYoga - Yoga Mats from the East # Website name
baseURL: 'https://www.luluyoga.shop/' # Website URL

############################
## PAGE OPTIONS
############################
#Control page features for an entire collection of pages by using Hugo cascades in hugo.yaml.
cascade:
  # Blog post options
  - _target:
      path: /blog/**
      kind: page
    pager: true
    editable: true
    hide_date: false
    show_date_updated: true
    reading_time: true
    commentable: true
    show_related: true
    share: true
    # Just use Breadcrumb for navigation on blog post pages?
    show_breadcrumb: false
    header:
      navbar:
        enable: true
  # Blog section options
  - _target:
      path: /blog/*
      kind: section
    # Set the listing view
    view: date-title-summary

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 95
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  author: authors
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
custom_css:
  - css/custom.css