# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Catalog
    weight: 20
    hasChildren: true
  - parent: Catalog
    name: Luxury Yoga Mat
    url: catalog/luxuryyogamat/
    weight: 30
  - parent: Catalog
    name: Foldable Yoga Mat
    url: foldableyogamat/
    weight: 40
  - parent: Catalog
    name: Artistic Travel Yoga Mat
    url: artistictravelyogamat/
    weight: 50
  - name: About Us
    url: aboutus/
    weight: 80
  - name: Resources
    weight: 60
    hasChildren: true
  - parent: Resources
    name: Blog
    url: blog/
    weight: 70
  - name: Contact
    url: contact/
    weight: 90