# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: OnlineBusiness
    local_business_type: ''
    org_name: ''
    description: 'LuluYoga - Yoga Mats From The East | Professional & Well-designed'
    twitter: ''
  analytics:
    # e.g. G-12345
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo.svg"
    button:
      enable: true
      text: "Buy Now"
      url: "https://hugoblox.com/templates/"
    show_search: true
    show_theme_chooser: true
    # Show a language chooser (if you have translated your site content)?
    # show_translations: false
    # If `show_translations` is enabled, do you wish to hide the current language name?
    # hide_language_name: false

# Site footer
footer:
  copyright:
    notice: '© {year} LuluYoga. '
  # For multilingual sites, show a language chooser in the footer?
  # show_translations: true

# Localization
locale:
  date_format: 'Jan 18, 2025'
  time_format: '15:04 PM'
